### ISSUE TITLE
Both the main and jazzy branches do not build with Ubuntu 24.04 Jazzy

### ISSUE THREAD

**Issue by altineller** [ros-navigation/navigation2#5587]
- Operating System: Ubuntu 24.04
- ROS2 Jazzy

Hello,

I wanted to use the latest navigation2 to work with keepout zones, because the documentation points for keepout filter points out to a version that is newer than Ubuntu 24.04 default package. I tried both the main and jazzy branch, but colcon build produced errors and failed. I am including error logs for the respective branches.

Best Regards,
C.

For the main branch:

In file included from /home/ros/workspaces/navigation2_ws/src/navigation2/nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp:46:
/opt/ros/jazzy/include/nav_2d_utils/conversions.hpp:43:10: fatal error: nav_2d_msgs/msg/path2_d.hpp: No such file or directory
   43 | #include "nav_2d_msgs/msg/path2_d.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/dwb_core.dir/build.make:76: CMakeFiles/dwb_core.dir/src/dwb_local_planner.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/dwb_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< dwb_core [16.9s, exited with code 2]
Aborted  <<< nav2_mppi_controller [16.9s]                                                                                                                              
Aborted  <<< nav2_constrained_smoother [22.9s]                                                                                                                         
Aborted  <<< costmap_queue [59.9s]                                                                                                                                       
Aborted  <<< nav2_navfn_planner [1min 28s]                                                                                                                                                       
Aborted  <<< nav2_planner [2min 2s]                                                                                                               
Aborted  <<< nav2_regulated_pure_pursuit_controller [2min 31s]                                                                                    
Aborted  <<< nav2_bt_navigator [2min 38s]                                                                                                                                             
Aborted  <<< nav2_controller [3min 23s]                                                                                                                                                
Aborted  <<< nav2_collision_monitor [4min 18s]                                                                                                                                    
Aborted  <<< nav2_behaviors [5min 25s]                                                                                            
Aborted  <<< nav2_route [9min 32s]                                            
                                         
Summary: 18 packages finished [30min 42s]
  1 package failed: dwb_core
  11 packages aborted: costmap_queue nav2_behaviors nav2_bt_navigator nav2_collision_monitor nav2_constrained_smoother nav2_controller nav2_mppi_controller nav2_navfn_planner nav2_planner nav2_regulated_pure_pursuit_controller nav2_route
  1 package had stderr output: dwb_core
  15 packages not processed

And for the jazzy branch:

--- stderr: nav2_behavior_tree                
In file included from /opt/ros/jazzy/src/gtest_vendor/include/gtest/gtest-printers.h:122,
                 from /opt/ros/jazzy/src/gtest_vendor/include/gtest/gtest-matchers.h:49,
                 from /opt/ros/jazzy/src/gtest_vendor/include/gtest/internal/gtest-death-test-internal.h:47,
                 from /opt/ros/jazzy/src/gtest_vendor/include/gtest/gtest-death-test.h:43,
                 from /opt/ros/jazzy/src/gtest_vendor/include/gtest/gtest.h:65,
                 from /home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:16:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp: In member function ‘virtual void PointPortTest_test_wrong_syntax_Test::TestBody()’:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:62:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
   62 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:25:
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:72:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
   72 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp: In member function ‘virtual void QuaternionPortTest_test_wrong_syntax_Test::TestBody()’:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:109:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  109 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:119:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  119 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp: In member function ‘virtual void PoseStampedPortTest_test_wrong_syntax_Test::TestBody()’:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:156:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  156 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:166:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  166 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp: In member function ‘virtual void PoseStampedVectorPortTest_test_wrong_syntax_Test::TestBody()’:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:210:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  210 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:220:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  220 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp: In member function ‘virtual void PathPortTest_test_wrong_syntax_Test::TestBody()’:
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:274:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  274 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
/home/ros/workspaces/nav2_ws/src/navigation2/nav2_behavior_tree/test/test_bt_utils.cpp:284:42: error: ignoring return value of ‘BT::Tree BT::BehaviorTreeFactory::createTreeFromText(const std::string&, BT::Blackboard::Ptr)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  284 |   EXPECT_THROW(factory.createTreeFromText(xml_txt), std::exception);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/opt/ros/jazzy/include/behaviortree_cpp/bt_factory.h:412:22: note: declared here
  412 |   [[nodiscard]] Tree createTreeFromText(
      |                      ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [test/CMakeFiles/test_bt_utils.dir/build.make:76: test/CMakeFiles/test_bt_utils.dir/test_bt_utils.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2003: test/CMakeFiles/test_bt_utils.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< nav2_behavior_tree [7min 14s, exited with code 2]
Aborted  <<< nav2_costmap_2d [4min 41s]      

Summary: 15 packages finished [11min 28s]
  1 package failed: nav2_behavior_tree
  1 package aborted: nav2_costmap_2d
  2 packages had stderr output: nav2_behavior_tree nav2_costmap_2d
  27 packages not processed

**Comment by SteveMacenski** [comment]
Our CI is passing, so it definitely builds jazzy on jazzy and rolling on main. Try cleaning your workspace, rebuilding from a clean source.

**Comment by altineller** [comment]
I started an lxd container and installed ros-jazzy-desktop and ros-dev-tools and then made the rosdep installation from the src dir, then proceeded to colcon build, and it did not give any error.

I probably have to uninstall a number of packages or the whole navigation package from my local ros install.
